//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rundown.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Issues
    {
        public int IssueId { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public Nullable<int> StatusId { get; set; }
        public Nullable<System.DateTime> ExpectedResolutionDate { get; set; }
        public Nullable<System.DateTime> ActualResolutionDate { get; set; }
        public bool IsDeleted { get; set; }
    
        public virtual Statuses Statuses { get; set; }
    }
}
